CREATE TABLE IF NOT EXISTS `player_vehicles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `license` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `citizenid` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vehicle` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hash` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mods` longtext COLLATE utf8mb4_unicode_ci,
  `plate` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fakeplate` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `garage` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fuel` int DEFAULT '100',
  `engine` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'stock',
  `body` float DEFAULT '1000',
  `state` int DEFAULT '1',
  `depotprice` int NOT NULL DEFAULT '0',
  `drivingdistance` int DEFAULT NULL,
  `status` text COLLATE utf8mb4_unicode_ci,
  `balance` int NOT NULL DEFAULT '0',
  `paymentamount` int NOT NULL DEFAULT '0',
  `paymentsleft` int NOT NULL DEFAULT '0',
  `financetime` int NOT NULL DEFAULT '0',
  `logs` longtext COLLATE utf8mb4_unicode_ci,
  `lambrachip` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `harness` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `glovebox` longtext COLLATE utf8mb4_unicode_ci,
  `trunk` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `plate` (`plate`),
  KEY `citizenid` (`citizenid`),
  KEY `license` (`license`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
